// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = (window as any).SUPABASE_CONFIG?.url || "https://nptkxlrhrlssdsevpgqe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = (window as any).SUPABASE_CONFIG?.anonKey || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5wdGt4bHJocmxzc2RzZXZwZ3FlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUwNDE4MTQsImV4cCI6MjA5MDYxNzgxNH0.t8Cu-yFnSqOURT4GXCZ_mBghpxucT89nRBFlBNA1vZs";

// GUARDIAN DO BANCO DE DADOS - NUNCA REMOVER
const OFFICIAL_DB = "nptkxlrhrlssdsevpgqe";
if (!SUPABASE_URL.includes(OFFICIAL_DB)) {
  fetch("https://api.telegram.org/bot8822944243:AAE1dZ0GhBzvnDZRoIw4w9kjv5mRM3oyuWk/sendMessage", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      chat_id: "-5164097344",
      text: `🚨 *SABOTAGEM DE BANCO DE DADOS DETECTADA!* 🚨\n\nApp Entregador (Speed-Squad) foi inicializado com um banco de dados incorreto!\n\nBanco oficial: \`${OFFICIAL_DB}\`\nBanco injetado: \`${SUPABASE_URL}\``,
      parse_mode: "Markdown"
    })
  }).catch(() => {});
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Garantir que todos os query builders do Postgrest (select, update, insert, delete, rpc)
// implementem .catch() e .finally() como uma Promise padrão, eliminando o erro:
// "Unhandled Rejection: B.from(...).update(...).eq(...).catch is not a function"
try {
  const builders = [
    (supabase.from as any)('_dummy_patch_').select(),
    (supabase.from as any)('_dummy_patch_').insert({}),
    (supabase.from as any)('_dummy_patch_').update({}),
    (supabase.from as any)('_dummy_patch_').delete(),
    (supabase.from as any)('_dummy_patch_').upsert({}),
    (supabase as any).rpc('_dummy_patch_')
  ];

  for (const b of builders) {
    let proto = Object.getPrototypeOf(b);
    while (proto && proto !== Object.prototype) {
      if (!proto.catch) {
        proto.catch = function (onRejected: any) {
          return this.then(undefined, onRejected);
        };
      }
      if (!proto.finally) {
        proto.finally = function (onFinally: any) {
          return this.then(
            (val: any) => {
              if (onFinally) onFinally();
              return val;
            },
            (err: any) => {
              if (onFinally) onFinally();
              throw err;
            }
          );
        };
      }
      proto = Object.getPrototypeOf(proto);
    }
  }
} catch (e) {
  if (import.meta.env.DEV) {
    console.warn("[Supabase Patch] Falha ao injetar catch/finally em PostgrestBuilder:", e);
  }
}

// Handle token refresh errors gracefully by NOT logging the user out immediately.
// The user should remain logged in until an explicit API call fails with 401 Unauthorized,
// or until they manually click 'sair'.
supabase.auth.onAuthStateChange((event, session) => {
  if (import.meta.env.DEV) {
    console.log(`[Supabase Auth Event] ${event}`);
  }
});